server:
  port: 8100  # Gateway port

spring:
  cloud:
    gateway:
      routes:
        - id: loanModule
          uri: http://localhost:8080  # Backend service
          predicates:
            - Path=/v1/users/**